[project]
name = 'contracts'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.expensess-factori]
path = 'contracts/expense-factory.clar'
clarity_version = 3
epoch = '3.1'

[contracts.groups-treasuri]
path = 'contracts/group-treasury.clar'
clarity_version = 3
epoch = 'latest'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
